universe 		= docker
docker_image 		= tensorflow/tensorflow:latest-gpu
executable              = 
output                  = red_patterns.$(ClusterId).$(ProcId).out
error                   = red_patterns.$(ClusterId).$(ProcId).err
log                     = red_patterns.$(ClusterId).log
should_transfer_files   = YES
request_GPUs = 1
request_CPUs = 1
request_memory = 6G
requirements = UidDomain == "cs.uni-saarland.de" 
+WantGPUHomeMounted = true
+WantScratchMounted = true
queue 1
